apiVersion: v1
kind: Service
metadata:
  name: k8s-devops-service
spec:
  type: NodePort
  selector:
    app: k8s-devops-project
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30090
